#!/usr/bin/env python3
"""
Environment Setup Script for iFake Deepfake Detection Platform
This script helps you configure environment variables including API keys.
"""

import os
import sys
from pathlib import Path

def create_env_file():
    """Create a .env file with user input"""
    print("🔧 Setting up environment configuration for iFake Deepfake Detection Platform")
    print("=" * 70)
    
    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists():
        response = input("⚠️  .env file already exists. Overwrite? (y/N): ").strip().lower()
        if response != 'y':
            print("❌ Setup cancelled.")
            return False
    
    # Get user input for configuration
    print("\n📝 Please provide the following configuration values:")
    print("(Press Enter to use default values or skip optional fields)")
    
    # Required configurations
    secret_key = input("\n🔐 Secret Key (32+ characters, for JWT tokens): ").strip()
    if not secret_key:
        secret_key = "your-super-secret-key-32-chars-minimum-change-in-production"
        print("   Using default secret key (⚠️  CHANGE IN PRODUCTION!)")
    
    # Optional API keys
    print("\n🤖 External AI API Keys (Optional - for enhanced detection):")
    print("   These are optional. The system works without them using fallback analysis.")
    
    openai_key = input("🔑 OpenAI API Key (get from https://platform.openai.com/api-keys): ").strip()
    gemini_key = input("🔑 Gemini API Key (get from https://makersuite.google.com/app/apikey): ").strip()
    
    # Email configuration
    print("\n📧 Email Configuration (Optional - for user verification):")
    smtp_host = input("📮 SMTP Host (default: smtp.gmail.com): ").strip() or "smtp.gmail.com"
    smtp_port = input("📮 SMTP Port (default: 587): ").strip() or "587"
    smtp_username = input("📮 SMTP Username: ").strip()
    smtp_password = input("📮 SMTP Password: ").strip()
    
    # Create .env content
    env_content = f"""# Environment Configuration for iFake Deepfake Detection Platform
# Generated by setup_environment.py

# Development Mode (set to false for production)
DEVELOPMENT_MODE=true

# Database Configuration
DATABASE_URL=sqlite:///./ifake_auth.db

# Redis Configuration
REDIS_URL=redis://localhost:6379

# Security Configuration
SECRET_KEY={secret_key}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7

# CORS Configuration
CORS_ORIGINS=http://localhost:3000,http://localhost:5173,https://ifake.com

# Email Configuration
SMTP_HOST={smtp_host}
SMTP_PORT={smtp_port}
SMTP_USERNAME={smtp_username}
SMTP_PASSWORD={smtp_password}

# API Configuration
API_RATE_LIMIT_ENABLED=true
API_KEY_LENGTH=32

# Security Headers
SECURITY_HEADERS_ENABLED=true

# Logging Configuration
LOG_LEVEL=INFO
AUDIT_LOG_ENABLED=true

# File Upload Configuration
MAX_FILE_SIZE_MB=100
ALLOWED_FILE_TYPES=image/jpeg,image/png,image/gif,image/webp,video/mp4,video/avi,video/mov,video/wmv

# Detection Configuration
DETECTION_TIMEOUT_SECONDS=300
MAX_CONCURRENT_DETECTIONS=10

# Monitoring Configuration
SECURITY_MONITORING_ENABLED=true
ALERT_EMAIL=security@ifake.com

# External AI API Keys (Optional - for enhanced detection)
OPENAI_API_KEY={openai_key}
GEMINI_API_KEY={gemini_key}

# Note: OpenAI and Gemini API keys are optional.
# The system will work without them using fallback analysis.
# Set these environment variables to enable full GPT-4V and Gemini analysis capabilities.
"""
    
    # Write .env file
    try:
        with open(".env", "w") as f:
            f.write(env_content)
        
        print("\n✅ Environment configuration saved to .env file!")
        
        # Show summary
        print("\n📋 Configuration Summary:")
        print(f"   🔐 Secret Key: {'✅ Set' if secret_key != 'your-super-secret-key-32-chars-minimum-change-in-production' else '⚠️  Using default (change in production!)'}")
        print(f"   🤖 OpenAI API Key: {'✅ Set' if openai_key else '❌ Not set (using fallback analysis)'}")
        print(f"   🤖 Gemini API Key: {'✅ Set' if gemini_key else '❌ Not set (using fallback analysis)'}")
        print(f"   📧 Email Config: {'✅ Set' if smtp_username else '❌ Not set'}")
        
        if not openai_key and not gemini_key:
            print("\n💡 Tip: To enable enhanced AI detection, set your API keys:")
            print("   - OpenAI: https://platform.openai.com/api-keys")
            print("   - Gemini: https://makersuite.google.com/app/apikey")
            print("   Then run this script again or manually edit the .env file.")
        
        return True
        
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")
        return False

def load_env_file():
    """Load environment variables from .env file"""
    env_file = Path(".env")
    if not env_file.exists():
        print("❌ .env file not found. Run setup_environment.py first.")
        return False
    
    try:
        with open(".env", "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    os.environ[key.strip()] = value.strip()
        return True
    except Exception as e:
        print(f"❌ Error loading .env file: {e}")
        return False

def check_api_keys():
    """Check if API keys are properly configured"""
    print("\n🔍 Checking API key configuration...")
    
    openai_key = os.getenv('OPENAI_API_KEY')
    gemini_key = os.getenv('GEMINI_API_KEY')
    
    print(f"   🤖 OpenAI API Key: {'✅ Configured' if openai_key else '❌ Not configured'}")
    print(f"   🤖 Gemini API Key: {'✅ Configured' if gemini_key else '❌ Not configured'}")
    
    if not openai_key and not gemini_key:
        print("\n⚠️  No external AI API keys configured.")
        print("   The system will use fallback analysis methods.")
        print("   For enhanced detection, consider setting up API keys.")
        return False
    
    return True

def main():
    """Main setup function"""
    print("🚀 iFake Deepfake Detection Platform - Environment Setup")
    print("=" * 60)
    
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        # Just check current configuration
        if load_env_file():
            check_api_keys()
        return
    
    # Interactive setup
    if create_env_file():
        print("\n🎉 Setup complete! You can now start the application.")
        print("\n📖 Next steps:")
        print("   1. Review the .env file and adjust settings as needed")
        print("   2. Start the application with: python start_app.py")
        print("   3. Check configuration with: python setup_environment.py --check")
    else:
        print("\n❌ Setup failed. Please try again.")

if __name__ == "__main__":
    main()
